//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testovaya.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PenisEntities : DbContext
    {
        private static PenisEntities _context;
        public static PenisEntities GetContext()
        {
            if (_context == null)
                _context = new PenisEntities();
            return _context;
        }
        public PenisEntities()
            : base("name=PenisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Sotrudnikii> Sotrudnikii { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
