//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testovaya.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnikii
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public System.DateTime Date { get; set; }
        public string Dolzhnost { get; set; }
        public int Number { get; set; }
        public string Family { get; set; }
        public string Adress { get; set; }
    }
}
